
package cn.edu.nju.jw.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthControllerService", targetNamespace = "http://jw.nju.edu.cn/schema", wsdlLocation = "http://106.15.183.234:8080/soap-api/auth?wsdl")
public class AuthControllerService
    extends Service
{

    private final static URL AUTHCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHCONTROLLERSERVICE_EXCEPTION;
    private final static QName AUTHCONTROLLERSERVICE_QNAME = new QName("http://jw.nju.edu.cn/schema", "AuthControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://106.15.183.234:8080/soap-api/auth?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHCONTROLLERSERVICE_WSDL_LOCATION = url;
        AUTHCONTROLLERSERVICE_EXCEPTION = e;
    }

    public AuthControllerService() {
        super(__getWsdlLocation(), AUTHCONTROLLERSERVICE_QNAME);
    }

    public AuthControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHCONTROLLERSERVICE_QNAME, features);
    }

    public AuthControllerService(URL wsdlLocation) {
        super(wsdlLocation, AUTHCONTROLLERSERVICE_QNAME);
    }

    public AuthControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHCONTROLLERSERVICE_QNAME, features);
    }

    public AuthControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyAuth
     */
    @WebEndpoint(name = "MyAuthPort")
    public MyAuth getMyAuthPort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/schema", "MyAuthPort"), MyAuth.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyAuth
     */
    @WebEndpoint(name = "MyAuthPort")
    public MyAuth getMyAuthPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/schema", "MyAuthPort"), MyAuth.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHCONTROLLERSERVICE_EXCEPTION!= null) {
            throw AUTHCONTROLLERSERVICE_EXCEPTION;
        }
        return AUTHCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
