
package cn.edu.nju.jw.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyAuth", targetNamespace = "http://jw.nju.edu.cn/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyAuth {


    /**
     * 
     * @param parameters
     * @return
     *     returns cn.edu.nju.jw.schema.验证类型
     * @throws IdNotFoundException
     * @throws PswErrorException
     */
    @WebMethod(action = "auth/verify")
    @WebResult(name = "\u9a8c\u8bc1\u4fe1\u606f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    @Action(input = "auth/verifyRequest", output = "auth/verifyResponse", fault = {
        @FaultAction(className = PswErrorException.class, value = "auth/verify/Fault/PswErrorException"),
        @FaultAction(className = IdNotFoundException.class, value = "auth/verify/Fault/IdNotFoundException")
    })
    public 验证类型 verify(
        @WebParam(name = "\u8ba4\u8bc1\u8bf7\u6c42", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
        账号认证类型 parameters)
        throws IdNotFoundException, PswErrorException
    ;

}
