
package cn.edu.nju.jw.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import cn.edu.nju.jw.schema.学生列表信息;
import cn.edu.nju.jw.schema.学生类型;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "studentManagementInterface", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    cn.edu.nju.jw.schema.ObjectFactory.class,
    cn.edu.nju.jw.wsdl.ObjectFactory.class,
    cn.edu.nju.schema.ObjectFactory.class
})
public interface StudentManagementInterface {


    /**
     * 
     * @param none
     * @return
     *     returns cn.edu.nju.jw.schema.学生列表信息
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/getAllStudents")
    @WebResult(name = "studentList", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "list")
    public 学生列表信息 getAllStudents(
        @WebParam(name = "none", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "none")
        NoneType none);

    /**
     * 
     * @param checkInfo
     * @return
     *     returns cn.edu.nju.jw.wsdl.验证信息
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/checkStudent")
    @WebResult(name = "isCorrect", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "checkResponse")
    public 验证信息 checkStudent(
        @WebParam(name = "studentInfo", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "checkInfo")
        学生类型 checkInfo);

    /**
     * 
     * @param addInfo
     * @return
     *     returns java.lang.String
     * @throws AddInfoFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/addStudent")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "updateSuccess")
    public String addStudent(
        @WebParam(name = "studentInfo", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "addInfo")
        学生类型 addInfo)
        throws AddInfoFault
    ;

    /**
     * 
     * @param updateInfo
     * @return
     *     returns java.lang.String
     * @throws UpdateInfoFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/updateStudent")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "updateSuccess")
    public String updateStudent(
        @WebParam(name = "studentInfo", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "updateInfo")
        学生类型 updateInfo)
        throws UpdateInfoFault
    ;

    /**
     * 
     * @param deleteInfo
     * @return
     *     returns java.lang.String
     * @throws DeleteInfoFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/deleteStudent")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "deleteSuccess")
    public String deleteStudent(
        @WebParam(name = "studentInfo", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "deleteInfo")
        学生类型 deleteInfo)
        throws DeleteInfoFault
    ;

}
