
package cn.edu.nju.jw.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import cn.edu.nju.jw.schema.课程成绩列表类型;
import cn.edu.nju.jw.schema.课程成绩类型;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScoreInterface", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    cn.edu.nju.jw.schema.ObjectFactory.class,
    cn.edu.nju.jw.wsdl.schema.ObjectFactory.class,
    cn.edu.nju.schema.ObjectFactory.class
})
public interface ScoreInterface {


    /**
     * 
     * @param studentNo
     * @return
     *     returns cn.edu.nju.jw.schema.课程成绩列表类型
     * @throws SearchScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/searchScore")
    @WebResult(name = "scoreList", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "scoreList")
    public 课程成绩列表类型 searchScore(
        @WebParam(name = "studentNo", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "studentNo")
        String studentNo)
        throws SearchScoreFault
    ;

    /**
     * 
     * @param addScore
     * @return
     *     returns java.lang.String
     * @throws AddScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/addScore")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "isSuccess")
    public String addScore(
        @WebParam(name = "score", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "addScore")
        课程成绩类型 addScore)
        throws AddScoreFault
    ;

    /**
     * 
     * @param delScore
     * @return
     *     returns java.lang.String
     * @throws DeleteScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/deleteScore")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "isSuccess")
    public String deleteScore(
        @WebParam(name = "score", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "delScore")
        课程成绩类型 delScore)
        throws DeleteScoreFault
    ;

    /**
     * 
     * @param modSocre
     * @return
     *     returns java.lang.String
     * @throws ModifyScoreFault
     */
    @WebMethod(action = "http://jw.nju.edu.cn/wsdl/modifyScore")
    @WebResult(name = "isSuccess", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "isSuccess")
    public String modifyScore(
        @WebParam(name = "score", targetNamespace = "http://jw.nju.edu.cn/wsdl/schema", partName = "modSocre")
        课程成绩类型 modSocre)
        throws ModifyScoreFault
    ;

}
